#!/bin/bash

if [[ -z $1 ]] || [[ -d $1 ]] ; then
	cd $1
	explorer.exe .
elif [[ -f $1 ]]; then
	WSL_DIR=$(dirname "${1}")
	WSL_FILE=$(basename "${1}")
	cd $WSL_DIR
	cmd.exe /c start "" "${WSL_FILE}"
else
	echo "Invalid Argument: ${1}"
	exit 1
fi

