#!/bin/bash

PWD=$(pwd)
WSL_PATH=$1

if [[ -d $WSL_PATH ]]; then
	WIN_PATH=$(wslpath -w $WSL_PATH)
	cmd.exe /c start "" "${WIN_PATH}"
elif [[ -f $WSL_PATH ]]; then
	WSL_DIR=$(dirname "${WSL_PATH}")
	WSL_FILE=$(basename "${WSL_PATH}")
	cd $WSL_DIR
	cmd.exe /c start "" "${WSL_FILE}"
else
	echo "Invalid Argument: ${WSL_PATH}"
	exit 1
fi
