#!/bin/bash

PWD=$(pwd)
WSL_PATH=$1
WIN_PATH=$(wslpath -w $WSL_PATH)

if [[ -d $WSL_PATH ]]; then
	echo "$WSL_PATH is a directory"
	cmd.exe /c start "" "$WIN_PATH"
elif [[ -f $WSL_PATH ]]; then
	echo "$WSL_PATH is a file"
else
	echo "$WSL_PATH is not valid"
	exit 1
fi
